### Dimensional of the feature map

In [1]:
import tensorflow as tf;

2025-05-25 14:08:11.701552: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [10]:
# Define input data (4D tensor), e.g., a batch of 1 image (4x4) with 1 channel
input_data = tf.constant([
    [
        [0,0,1,2],
        [0,0,2,0],
        [0,0,0,2],
        [0,0,1,2],
        [0,0,0,2],
        [0,0,2,0],
        [0,0,1,2]
    ]
], dtype=tf.float32)

print("original input data: ", input_data)

# Reshape to match the expected 4D input `[batch, height, width, channels]`
input_data = tf.reshape(input_data, [1, 7, 4, 1])
print(input_data)

original input data:  tf.Tensor(
[[[0. 0. 1. 2.]
  [0. 0. 2. 0.]
  [0. 0. 0. 2.]
  [0. 0. 1. 2.]
  [0. 0. 0. 2.]
  [0. 0. 2. 0.]
  [0. 0. 1. 2.]]], shape=(1, 7, 4), dtype=float32)
tf.Tensor(
[[[[0.]
   [0.]
   [1.]
   [2.]]

  [[0.]
   [0.]
   [2.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   [2.]]

  [[0.]
   [0.]
   [1.]
   [2.]]

  [[0.]
   [0.]
   [0.]
   [2.]]

  [[0.]
   [0.]
   [2.]
   [0.]]

  [[0.]
   [0.]
   [1.]
   [2.]]]], shape=(1, 7, 4, 1), dtype=float32)


In [13]:
# Define a 3x3 filter (kernel) with 1 input channel and 1 output channel
filter_weights = tf.constant([
    [[-1,-1,1],
    [-1, -1, 1],
    [-1, -1, 1]]
], dtype=tf.float32)
print(filter_weights)

# Reshape to match the expected filter shape `[filter_height, filter_width, in_channels, out_channels]`
filter_weights = tf.reshape(filter_weights, [3,3,1,1])
print("filter weight after reshape: ", filter_weights)

tf.Tensor(
[[[-1. -1.  1.]
  [-1. -1.  1.]
  [-1. -1.  1.]]], shape=(1, 3, 3), dtype=float32)
filter weight after reshape:  tf.Tensor(
[[[[-1.]]

  [[-1.]]

  [[ 1.]]]


 [[[-1.]]

  [[-1.]]

  [[ 1.]]]


 [[[-1.]]

  [[-1.]]

  [[ 1.]]]], shape=(3, 3, 1, 1), dtype=float32)


In [ ]:
# Strides: [batch_stride, height_stride, width_stride, channel_stride]
strides = [1,2,1,1] # Setting stride to 2 for height and 1 width

# padding can either 'SAME' or 'VALID'
padding = 'VALID'

# Perform 2D convolution
output = tf.nn.conv2d(input=input_data, filters=filter_weights, strides=strides, padding=padding)

In [24]:
print(tf.reshape(output, [3,2]))

tf.Tensor(
[[3. 1.]
 [1. 5.]
 [3. 1.]], shape=(3, 2), dtype=float32)
