# Exercise 01
### Name: Seth Rattanak
### PART A
Compute the minimum edit distance between
each of the following pair of strings (draw the edit distance
table) and then find the appropriate alignments:
1. “APPROXIMATION”, “INFORMATIONAL”
2. “AGGCTATCACCTGA”, “TAGCTATCACGA”
3. "បច្ចប្ប័ន្នភាព្ព", "បច្ចុប្បន្នភាព"

In [ ]:
### EXERCISE 1.1

In [6]:
import numpy as np
from numpy._typing import (
    # Arrays
    NDArray
)
from typing import (
    Literal as L,
    Any,
    overload,
    TypeVar,
    SupportsIndex,
    final,
    Final,
    Protocol,
    ClassVar,
)

In [ ]:
word_1 = "_APPROXIMATION"
word_2 = "_INFORMATIONAL"
word_list_1 = list(word_1)
word_list_2 = list(word_2)

# initialize default table
table_list = np.empty((len(word_list_1), len(word_list_2)), np.int8)

for idx1, w1 in enumerate(word_list_1):
    for idx2, w2 in enumerate(word_list_2):
        # default Epsilon with word and word with Epsilon
        # print(idx1, "&", idx2)
        if (idx1 == 0):
            table_list[idx1][idx2] = idx2
        elif idx1 > 0 and idx2 < 1:
            table_list[idx1][idx2] = idx1
        else:
            # use minimum edit distance, ranging from [1, 1] till end
            # idx1 stand for Y or n; idx2 represent X or m
            edX = table_list[idx1][idx2 -1] + 1 #eD(m-1, n)
            edY = table_list[idx1 -1 ][idx2] + 1 # eD(m, n-1)
            diagonal = table_list[idx1 -1][idx2 -1] + (0 if w1 == w2 else 1) #eD(m-1,n-1) + delta(X[m], Y[n])
            table_list[idx1][idx2] = min(edX, edY, diagonal)

print(table_list)

shape:  (14, 14)
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]
 [ 1  1  2  3  4  5  6  6  7  8  9 10 11 12]
 [ 2  2  2  3  4  5  6  7  7  8  9 10 11 12]
 [ 3  3  3  3  4  5  6  7  8  8  9 10 11 12]
 [ 4  4  4  4  4  4  5  6  7  8  9 10 11 12]
 [ 5  5  5  5  4  5  5  6  7  8  8  9 10 11]
 [ 6  6  6  6  5  5  6  6  7  8  9  9 10 11]
 [ 7  6  7  7  6  6  6  7  7  7  8  9 10 11]
 [ 8  7  7  8  7  7  6  7  8  8  8  9 10 11]
 [ 9  8  8  8  8  8  7  6  7  8  9  9  9 10]
 [10  9  9  9  9  9  8  7  6  7  8  9 10 10]
 [11 10 10 10 10 10  9  8  7  6  7  8  9 10]
 [12 11 11 11 10 11 10  9  8  7  6  7  8  9]
 [13 12 11 12 11 11 11 10  9  8  7  6  7  8]]


### Create a function for clean code

In [51]:
def compute_minimum_edit_distance(word_1: str, word_2: str) -> NDArray[Any]:
    word_list_1 = list(word_1)
    word_list_2 = list(word_2)
    # initialize default table
    table_list = np.empty((len(word_list_1), len(word_list_2)), np.int8)

    for idx1, w1 in enumerate(word_list_1):
        for idx2, w2 in enumerate(word_list_2):
            # default Epsilon with word and word with Epsilon
            # print(idx1, "&", idx2)
            if (idx1 == 0):
                table_list[idx1][idx2] = idx2
            elif idx1 > 0 and idx2 < 1:
                table_list[idx1][idx2] = idx1
            else:
                # use minimum edit distance, ranging from [1, 1] till end
                # idx1 stand for Y or n; idx2 represent X or m
                edX = table_list[idx1][idx2 -1] + 1 #eD(m-1, n)
                edY = table_list[idx1 -1 ][idx2] + 1 # eD(m, n-1)
                diagonal = table_list[idx1 -1][idx2 -1] + (0 if w1 == w2 else 1) #eD(m-1,n-1) + delta(X[m], Y[n])
                table_list[idx1][idx2] = min(edX, edY, diagonal)

    return table_list

In [ ]:
# Exercise 1.2, similarly, _ use for space
word_1 = "_AGGCTATCACCTGA"
word_2 = "_TAGCTATCACGA"
print(compute_minimum_edit_distance(word_1=word_1, word_2=word_2))

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12]
 [ 1  1  1  2  3  4  5  6  7  8  9 10 11]
 [ 2  2  2  1  2  3  4  5  6  7  8  9 10]
 [ 3  3  3  2  2  3  4  5  6  7  8  8  9]
 [ 4  4  4  3  2  3  4  5  5  6  7  8  9]
 [ 5  4  5  4  3  2  3  4  5  6  7  8  9]
 [ 6  5  4  5  4  3  2  3  4  5  6  7  8]
 [ 7  6  5  5  5  4  3  2  3  4  5  6  7]
 [ 8  7  6  6  5  5  4  3  2  3  4  5  6]
 [ 9  8  7  7  6  6  5  4  3  2  3  4  5]
 [10  9  8  8  7  7  6  5  4  3  2  3  4]
 [11 10  9  9  8  8  7  6  5  4  3  3  4]
 [12 11 10 10  9  8  8  7  6  5  4  4  4]
 [13 12 11 10 10  9  9  8  7  6  5  4  5]
 [14 13 12 11 11 10  9  9  8  7  6  5  4]]


In [54]:
# Exercise 1.3, similarly, _ use for space
word_1 = "_បច្ចប្ប័ន្នភាព្ព"
word_2 = "_បច្ចុប្បន្នភាព"
print(compute_minimum_edit_distance(word_1=word_1, word_2=word_2))

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [ 1  0  1  2  3  4  5  6  7  8  9 10 11 12 13]
 [ 2  1  0  1  2  3  4  5  6  7  8  9 10 11 12]
 [ 3  2  1  0  1  2  3  4  5  6  7  8  9 10 11]
 [ 4  3  2  1  0  1  2  3  4  5  6  7  8  9 10]
 [ 5  4  3  2  1  1  1  2  3  4  5  6  7  8  9]
 [ 6  5  4  3  2  2  2  1  2  3  4  5  6  7  8]
 [ 7  6  5  4  3  3  2  2  1  2  3  4  5  6  7]
 [ 8  7  6  5  4  4  3  3  2  2  3  4  5  6  7]
 [ 9  8  7  6  5  5  4  4  3  2  3  3  4  5  6]
 [10  9  8  7  6  6  5  4  4  3  2  3  4  5  6]
 [11 10  9  8  7  7  6  5  5  4  3  2  3  4  5]
 [12 11 10  9  8  8  7  6  6  5  4  3  2  3  4]
 [13 12 11 10  9  9  8  7  7  6  5  4  3  2  3]
 [14 13 12 11 10 10  9  8  8  7  6  5  4  3  2]
 [15 14 13 12 11 11 10  9  9  8  7  6  5  4  3]
 [16 15 14 13 12 12 11 10 10  9  8  7  6  5  4]]


### PART B

In [1]:
from typing import Final

DELETE: Final[int] = 1
INSERT: Final[int] = 2
SUBSTITUTE: Final[int] = 3

In [7]:
# Make function bases on what studied in classroom (excel formula or minimum edit distance eD)
def compute_minimum_edit_distance_with_cost(word_1: str, word_2: str) -> dict:
    word_list_1 = list(word_1)
    word_list_2 = list(word_2)
    cost = 0
    delete = 0
    insert = 0
    substitute = 0
    # initialize default table
    table_list = np.empty((len(word_list_1), len(word_list_2)), np.int8)

    for idx1, w1 in enumerate(word_list_1):
        for idx2, w2 in enumerate(word_list_2):
            # default Epsilon with word and word with Epsilon
            # print(idx1, "&", idx2)
            if (idx1 == 0):
                table_list[idx1][idx2] = idx2
            elif idx1 > 0 and idx2 < 1:
                table_list[idx1][idx2] = idx1
            else:
                diagonal = table_list[idx1 -1][idx2 -1]
                if w1 == w2:
                    # Just copy the diagonal element. No cost then
                    table_list[idx1][idx2] = diagonal
                else: 
                    # can be replace remove, or insert
                    # use minimum edit distance, ranging from [1, 1] till end
                    # idx1 stand for Y or n; idx2 represent X or m
                    edX = table_list[idx1][idx2 -1] + 1 #eD(m-1, n), remove
                    edY = table_list[idx1 -1 ][idx2] + 1 # eD(m, n-1), insert
                    minimum = min(edX, edY, diagonal)
                    if minimum == edX:
                        # if minimum values are the same delete is prior
                        cost += DELETE
                        delete += DELETE
                    elif minimum == edY:
                        cost += INSERT
                        insert += INSERT
                    elif minimum == diagonal:
                        cost += SUBSTITUTE
                        substitute += SUBSTITUTE
                    table_list[idx1][idx2] = minimum + 1

    return {
        "table_list": table_list, 
        "total_cost": cost,
        "delete_cost": delete,
        "insert_cost": insert,
        "substitute": substitute
    }

In [10]:
word_orig = "_APPROXIMATION"
word_sub = "_INFORMATIONAL"

distance = compute_minimum_edit_distance_with_cost(word_orig, word_sub)
print("Cost of this operation: ", distance['total_cost'])
print("Cost of this delete: ", distance['delete_cost'])
print("Cost of this insert: ", distance['insert_cost'])
print("Cost of this substitute: ", distance['substitute'])

Cost of this operation:  397
Cost of this delete:  20
Cost of this insert:  38
Cost of this substitute:  339


In [11]:
word_1 = "_AGGCTATCACCTGA"
word_2 = "_TAGCTATCACGA"

distance: dict = compute_minimum_edit_distance_with_cost(word_1, word_2)
print("Cost of this operation: ", distance['total_cost'])
print("Cost of this delete: ", distance['delete_cost'])
print("Cost of this insert: ", distance['insert_cost'])
print("Cost of this substitute: ", distance['substitute'])

Cost of this operation:  269
Cost of this delete:  35
Cost of this insert:  72
Cost of this substitute:  162


In [12]:
word_1 = "_បច្ចប្ប័ន្នភាព្ព"
word_2 = "_បច្ចុប្បន្នភាព"
distance: dict = compute_minimum_edit_distance_with_cost(word_1, word_2)
print("Cost of this operation: ", distance['total_cost'])
print("Cost of this delete: ", distance['delete_cost'])
print("Cost of this insert: ", distance['insert_cost'])
print("Cost of this substitute: ", distance['substitute'])

Cost of this operation:  418
Cost of this delete:  49
Cost of this insert:  114
Cost of this substitute:  255
