### Max pooling

In [7]:
import tensorflow as tf
from tensorflow.python.keras.layers import MaxPooling2D
# from tensorflow.keras
 
# Define the input tensor
X = tf.constant([
    [3, 0, 1, 2, 7, 4],
    [1, 5, 8, 9, 3, 1],
    [2, 7, 2, 5, 1, 3],
    [0, 1, 3, 1, 7, 8],
    [4, 2, 1, 6, 2, 8],
    [2, 4, 5, 2, 3, 9]
])

filter = tf.constant([[[[1]], [[0]], [[-1]]],
                      [[[1]], [[0]], [[-1]]],
                      [[[1]], [[0]], [[-1]]]], dtype=tf.float32)
 
# Reshape the tensor to have batch and channel dimensions
X_reshaped = tf.reshape(X, [1, 6, 6, 1])
 
def maxPooling():
    # Create the max pooling layer
    max_pool_layer = MaxPooling2D(
        pool_size=2,    # Pool size: 2x2
        strides=1,      # Stride: 1x1
        padding='valid'      # No padding
    )
    
    # Apply pooling
    max_pooled = max_pool_layer(X_reshaped)
    
    # Reshape back to 2D
    result = tf.reshape(max_pooled, [-1, max_pooled.shape[2]])
    
    print("Original array:")
    print(X.numpy())
    print("\nAfter max pooling (pool size 2x2, stride 1x1):")
    print(result.numpy())
 
def dilation():
    dilation_model = tf.nn.conv2d(input=X_reshaped,padding=[[0,0],[0,0]],filters=filter, strides=1, dilations=2)
    # model_reshape = dilation_model(X_reshaped)
    
    # Reshape back to 2D
    result = tf.reshape(dilation_model, [-1, dilation_model.shape[2]])
    
    print("Original array:")
    print(X.numpy())
    print("\nAfter Dilation (padding size 2x2, stride 1x1):")
    print(result.numpy())

dilation()

ValueError: When padding is a list, it must be of size 4. Received: padding=[[0, 0], [0, 0]] of size 2

### Padding=VALID

In [18]:
data1 = tf.constant([
    [0,0,2,2],
    [0,0,2,2],
    [0,0,2,2],
    [0,0,2,2]
], dtype=tf.float32)
X_reshaped = tf.reshape(data1, [1,4,4,1])
# print(data1_reshape)

# Define the custom kernel
kernel = tf.constant([
    [-1, -1, 1],  
    [-1, -1, 1],  
    [-1, -1, 1],  
], dtype=tf.float32)

# Reshape the kernel to the format expected by tf.nn.conv2d [filter_height, filter_width, in_channels, out_channels]
kernel = tf.reshape(kernel, [3, 3, 1, 1])

# Reshape the kernel to the format expected by tf.nn.conv2d [filter_height, filter_width, in_channels, out_channels]
# kernel = tf.reshape(kernel, [3, 3, 1, 1])

# Apply convolution with padding='SAME' (which adds padding of 1) and stride of 2
conv_result = tf.nn.conv2d(
    input=X_reshaped,
    filters=kernel,
    strides=[1, 1, 1, 1],  # Stride of 2 in both height and width dimensions
    padding='SAME'         # Adds padding as needed (effectively padding of 1)
)

# Reshape back to 2D
result = tf.reshape(conv_result, [-1, conv_result.shape[2]])

print("Original array:")
print(X.numpy())
print("\nConvolution kernel:")
print(tf.reshape(kernel, [3, 3, 1]).numpy())
print("\nAfter convolution (kernel size 3x3, stride 1x1, padding=SAME):")
print(result.numpy())

Original array:
[[3 0 1 2 7 4]
 [1 5 8 9 3 1]
 [2 7 2 5 1 3]
 [0 1 3 1 7 8]
 [4 2 1 6 2 8]
 [2 4 5 2 3 9]]

Convolution kernel:
[[[-1.]
  [-1.]
  [ 1.]]

 [[-1.]
  [-1.]
  [ 1.]]

 [[-1.]
  [-1.]
  [ 1.]]]

After convolution (kernel size 3x3, stride 1x1, padding=SAME):
[[  0.   4.   0.  -8.]
 [  0.   6.   0. -12.]
 [  0.   6.   0. -12.]
 [  0.   4.   0.  -8.]]
